// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAuhSD5Smw8DYin9YRFm7Nvy6LY6rhs14',
    appId: '1:161040591855:web:04e8ae106591573b27a41a',
    messagingSenderId: '161040591855',
    projectId: 'chop-pedia',
    authDomain: 'chop-pedia.firebaseapp.com',
    storageBucket: 'chop-pedia.appspot.com',
    measurementId: 'G-K23K3Y0592',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdb4DayK21Dyxa1Hq8wUvss_Kt1tf4luA',
    appId: '1:161040591855:android:ce693d145aefb16727a41a',
    messagingSenderId: '161040591855',
    projectId: 'chop-pedia',
    storageBucket: 'chop-pedia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGGX9o_gCIbPUlqTHuQQt6zVa8k9hQmZc',
    appId: '1:161040591855:ios:32429fc4dda5c40627a41a',
    messagingSenderId: '161040591855',
    projectId: 'chop-pedia',
    storageBucket: 'chop-pedia.appspot.com',
    iosClientId:
        '161040591855-fnkhjjt81boj9ejh4456rmrqla8m7e04.apps.googleusercontent.com',
    iosBundleId: 'com.example.chopedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGGX9o_gCIbPUlqTHuQQt6zVa8k9hQmZc',
    appId: '1:161040591855:ios:32429fc4dda5c40627a41a',
    messagingSenderId: '161040591855',
    projectId: 'chop-pedia',
    storageBucket: 'chop-pedia.appspot.com',
    iosClientId:
        '161040591855-fnkhjjt81boj9ejh4456rmrqla8m7e04.apps.googleusercontent.com',
    iosBundleId: 'com.example.chopedia',
  );
}
